### ISSUE TITLE
Escrever Readme

### ISSUE THREAD

**Issue by Borghezane** [Borghezane/mvpPLPython#3]
- Como executar
- Como testar
- Descrever o problema e o modelo de instâncias

**Comment by jeanpttorres** [comment]
## Operação `init`

### Json Entrada

	{
	    nFornecedores: "3",
	    nClients: "5",
	    custoFornecedorCliente: [ 
		["1","2","3"],
		["5","7","5"],
		["3","9","2"],
		["9","1","4"],
		["1","154","13"]
	    ],
	    custoFornecedor: ["10","2","7"]
	}

### Json Saída

	{
	    id:"8075662",
	    password: "eTr#21@!!lop"
	}
	
### Exemplo de Requisição

**Comment by jeanpttorres** [comment]
## Operação `getSol`

### Json Entrada

Vazio.
Necessário enviar dados de autenticação `id:password`

### Json Saída

**Encerrado:**

 	 {
	     custo:"107",
	     solucao: ["0","1","1","0","1"]
	     encerrado: "true"
	 }


**Não Encerrado:**
	

	 {
	     custo:"-inf",
	     solucao: ["-1","-1","-1","-1","-1"]
	     encerrado: "false"
	 }
